### PR TITLE
Feat/upgrade rio tiler

### PR DESCRIPTION
**Pull request by abarciauskas-bgse**
## Changes
* Upgrades titiler to 0.14 via changes in #30 
* Updates the map form to use scientific notation for values less than 0.001
* Adds development deployment

### CODE REVIEW

**Comment by abarciauskas-bgse** [comment]
.deploy

**Comment by abarciauskas-bgse** [comment]
test

**Comment by abarciauskas-bgse** [comment]
@vincentsarago I can't seem to figure out what these errors are all about - can you take a look? 

example:
>ERROR tests/test_app.py::test_get_variables_reference - pydantic_core._pydantic_core.SchemaError: Invalid Schema:
definitions.definitions.6.model.schema.model-fields.fields.geometries.schema.function-after.schema.list.items_schema.tagged-union.choices.GeometryCollection
  Recursion error - cyclic reference detected [type=recursion_loop, input_value={'type': 'model', 'cls': ...lection:93865001497632'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/recursion_loop

https://github.com/developmentseed/titiler-xarray/actions/runs/6306145150/job/17120886537

**Comment by abarciauskas-bgse** [comment]
Resolved the test issue via pinning the version of pydantic to 2.1.2 😬

**Comment by vincentsarago** [comment]
😭 sorry @abarciauskas-bgse lost tracks of the PR/Issue. 

There was a breaking changes published with pydantic 2.4 😓 https://github.com/developmentseed/geojson-pydantic/issues/146

**Comment by abarciauskas-bgse** [comment]
No worries @vincentsarago and thanks for pointing out that issue. Do you think we should then update pyproject.yml with `pydantic>=2.0.2,<2.4`?

**Comment by vincentsarago** [comment]
@abarciauskas-bgse hopefully a new release a pydantic should happen soon so we don't have to worry

**Comment by abarciauskas-bgse** [comment]
Ok so do you think we should revert the pinned pydantic version? And if yes should we then hold this PR for the update to pydantic or ignore the failing tests?

**Comment by vincentsarago** [comment]
> Ok so do you think we should revert the pinned pydantic version? And if yes should we then hold this PR for the update to pydantic or ignore the failing tests?

I think it's fine to keep this as it is right now and we'll remove it later

**Review by vincentsarago — APPROVED** [review]

**Pull request merged**
