### PR TITLE
sketch profiling

### PR DESCRIPTION
**Pull request by vincentsarago**
Simple `profiler` to count the number of S3 GET request and get other statistics

```python
@profile(add_to_return=True, cprofile=True, quiet=True)
def get_tile(src_path: str, x: int, y: int, z: int, *, variable: str, **kwargs: Any):

    with xarray_open_dataset(
        src_path,
        z=z,
        **kwargs,
    ) as dataset:
        
        dataarray, _ = update_dataset(dataset, variable=variable)
        
        with XarrayReader(dataarray) as src_dst:
            return src_dst.tile(x, y, z)

_, logs = get_tile(
    "s3://power-analysis-ready-datastore/power_901_monthly_meteorology_utc.zarr", 
    4, 
    4, 
    4, 
    variable="TS",
)

print(logs)
{'GET': 52,
 'Timing': 5.186955213546753,
 'cprofile': ['   ncalls  tottime  percall  cumtime  percall filename:lineno(function)',
  "       40    4.844    0.121    4.844    0.121 {method 'acquire' of '_thread.lock' objects}",
  "        1    0.027    0.027    0.028    0.028 {method 'start' of 'rasterio._env.GDALEnv' objects}",
  '        8    0.017    0.002    0.021    0.003 core.py:2142(_decode_chunk)',
  '        1    0.015    0.015    0.015    0.015 {rasterio._warp._reproject}',
  '      408    0.011    0.000    0.015    0.000 typing.py:1065(_get_protocol_attrs)',
  '113732/112582    0.011    0.000    0.042    0.000 {built-in method builtins.isinstance}',
  '2221/2189    0.010    0.000    0.014    0.000 indexing.py:512(shape)',
  '        9    0.007    0.001    0.007    0.001 crs.py:183(__init__)',
  '     2437    0.006    0.000    0.082    0.000 variable.py:194(as_compatible_data)',
  '39365/33478    0.004    0.000    0.005    0.000 {built-in method builtins.len}']}

```

### CODE REVIEW

**Comment by sharkinsspatial** [comment]
Martin raises a good question here https://github.com/pydata/xarray/issues/6033#issuecomment-1020190813 that we should first be trying to understand if `xarray` is loading chunks serially or concurrently.

**Comment by sharkinsspatial** [comment]
https://github.com/pydata/xarray/issues/1385

**Comment by abarciauskas-bgse** [comment]
@vincentsarago - @sharkinsspatial discussed today if we could compare tiling using XarrayReader and pgstac. I started to look into how to do this, and noticed you have some code setup in titiler-pgstac to load some items into a local pgstac instance and then use siege, https://github.com/stac-utils/titiler-pgstac/tree/main/benchmark (I know you have mentioned this before)

I started to work on creating a simplified version of the tile method in pgstac for code profiling here: https://github.com/stac-utils/titiler-pgstac/compare/main...abarciauskas-bgse:titiler-pgstac:ab/wip-simple-pgstac-profiling?expand=1 but I'm pretty new to that codebase so if you have any feedback let me know - should I open an issue in that repo for profiling as well?

**Comment by abarciauskas-bgse** [comment]
@vincentsarago thanks for this - I agree that we need to put more thought into the approach to compare COG with Zarr tiling performance. Do you mind putting ⬆️ comments in the discussion https://github.com/stac-utils/titiler-pgstac/discussions/97 as well?

**Comment by abarciauskas-bgse** [comment]
@vincentsarago is it ok if we close this since the work has moved to https://github.com/developmentseed/tile-benchmarking?

**Comment by vincentsarago** [comment]
👍

**Pull request closed without merging**
