### PR TITLE
Add multiscale

### PR DESCRIPTION
**Pull request by vincentsarago**
Creating this PR for visibility

cc @abarciauskas-bgse

### CODE REVIEW

**Comment by yoninachmany** [comment]
👋 Thanks for this work! Is there any public data that you're using with this PR or project that I could try out? 🙏

**Comment by abarciauskas-bgse** [comment]
@yoninachmany I am using it in a deployment of titiler-xarray used in [https://github.com/developmentseed/zarr-viz-explorations](https://github.com/developmentseed/zarr-viz-explorations/blob/main/main.ts) and accessible via http://devseed.com/zarr-viz-explorations/. You can see the datasets in there that I have created with multiple scales (those with "pyramid" in the name, however I believe access to the bucket is protected at this time. I _think_ I deployed a titiler instance using this branch and that the `titiler-xarray` directory in that repo was for testing, but it's been awhile so I would have to double check my notes.

**Comment by yoninachmany** [comment]
Thanks so much @abarciauskas-bgse! Just checking, https://github.com/developmentseed/zarr-viz-explorations is currently private - should it be public?

**Comment by yoninachmany** [comment]
A virtual chat about titiler-xarray and what you're testing would be excellent!

**Comment by abarciauskas-bgse** [comment]
closing in favor of #2

**Pull request closed without merging**
